#pragma once

#define WIFI_SSID        "YOUR_WIFI_SSID"
#define WIFI_PASSWORD    "YOUR_WIFI_PASSWORD"

#define Web_API_KEY      "YOUR_FIREBASE_WEB_API_KEY"
#define DATABASE_URL     "YOUR_FIREBASE_DATABASE_URL"
#define USER_EMAIL       "YOUR_FIREBASE_AUTH_EMAIL"
#define USER_PASS        "YOUR_FIREBASE_AUTH_PASSWORD"
